apiVersion: apps/v1
kind: Deployment
metadata:
  name: miscsync
spec:
  selector:
    matchLabels:
      app: miscsync
  template:
    metadata:
      labels:
        app: miscsync
    spec:
      containers:
      - name: miscsync
        image: ghcr.io/evebot-tools/miscsync
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        # ports:
        # - containerPort: 3000
        #   protocol: TCP
        #   name: http
        env:
        - name: PORT
          value: "3000"
        - name: ENVIRONMENT
          valueFrom:
            secretKeyRef:
              key: ENVIRONMENT
              name: evetools-secrets
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              key: SENTRY_APPNAME
              name: evetools-secrets